# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'RxExample_PublishSubject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxExample_PublishSubject
    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'

end
