# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FC_Github' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'RxSwift', '6.5.0'
	pod 'RxCocoa', '6.5.0'

  # Pods for FC_Github

  target 'FC_GithubTests' do
    inherit! :search_paths
    # Pods for testing
		pod 'RxSwift', '6.5.0'
		pod 'RxCocoa', '6.5.0'
  end

  target 'FC_GithubUITests' do
    # Pods for testing
		pod 'RxSwift', '6.5.0'
		pod 'RxCocoa', '6.5.0'
  end

end
